#version: '3.8' # Docker Compose 文件的版本

services:
  aliyuncicdservice: # 服务名称，可以根据需要进行更改
    build:
      context: . # Dockerfile 的路径，'.' 表示当前目录
      dockerfile: Dockerfile # Dockerfile 的文件名，如果文件名是 Dockerfile 则可以省略
    ports:
      - "9084:80" # 将容器的 80 端口映射到主机的 8080 端口，可以根据需要更改
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=Development # 设置环境变量，可以根据需要添加更多

# 如果有多个服务，可以在这里定义
