# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  cicdweb:
    image: cicdweb
    build:
      context: .
      dockerfile: src/CICDWeb/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5137:5137
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
