name: Deploy to Cloud Server

on:
  push:
    branches:
      - master
      
jobs:

  # 定义测试作业
  test:
    runs-on: ubuntu-latest

    steps:
      # 检出 master 分支上的代码
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      # 设置 .NET 环境
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'  # 确保使用适当的 .NET Core 版本

      # 还原依赖项
      - name: Restore dependencies
        run: dotnet restore

      # 构建项目
      - name: Build the project
        run: dotnet build --configuration Release

      # 运行测试
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出 master 分支上的代码
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master  # 指定检出 master 分支

      #- name: Set up .NET
      #  uses: actions/setup-dotnet@v2
      #  with:
      #    dotnet-version: '7.0'  # 确保使用适当的 .NET Core 版本

      #- name: Restore dependencies
      #  run: dotnet restore

      #- name: Build the project
      #  run: dotnet publish -c Release -o out

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" . root@119.12.165.28:/root/deploy/aliyuncicd/deploy

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no root@119.12.165.28 << 'EOF'
          cd /root/deploy/aliyuncicd/deploy
          docker compose down
          docker compose up -d --build --remove-orphans
          EOF

      # 清理无用的镜像
      - name: Cleanup Docker images
        run: |
          ssh -o StrictHostKeyChecking=no root@119.12.165.28 << 'EOF'
          docker image prune -f
          EOF